version: "3.7"
services:
  #mysql
  mysql:
    image:  mysql:latest
    volumes:
      - ./data/configs/sql:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=csa
      - MYSQL_ROOT_PASSWORD=123456


  #Redis
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ./data/data/redis:/data
      - ./data/logs/redis:/logs
    command: redis-server --requirepass 123456