version: "3.7"
services:
  #mysql
  mysql:
    image:  mysql:latest
    volumes:
      - ./data/configs/sql:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=csa
      - MYSQL_ROOT_PASSWORD=123456